### PR TITLE
Update Select2 to 4.0.13 (and jQuery to 3.1.5, fixes #65)

### LINKED ISSUE #65: Update included version to 4.0.13
I just noticed the included version appears to be pinned to 4.0.0, which was released about 5 years ago. Looking through the code, there shouldn't be anything breaking when doing this change and it will fix a lot of accessibility and browser compatibility issues that have been spotted over the years.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #65

### CODE REVIEW

**Comment by asyncee** [comment]
I will merge that PR because it looks good to me.

**Comment by asyncee** [comment]
This fix will be unreleased until i (or someone else) will test it.

**Comment by hartwork** [comment]
> This fix will be unreleased until i (or someone else) will test it.

@leibowitz @kevin-brown @jaikanthjay46 do you have a minute to confirm that things are stil working on `master`?

**Comment by leibowitz** [comment]
at first glance, all looking fine 👍

**Comment by asyncee** [comment]
I have merged #67, #69, #70, #72, #73, #74 in last few days because those PRs were small, simple and valuable. Sadly i have no time right now to test all those changes before release.

If someone can confirm that everything is fine on latest Django, i will be happy to make new release.

**Pull request merged**
