### PR TITLE
setup.py; exclude tests

### PR DESCRIPTION
**Pull request by ms-boom**

### CODE REVIEW

**Comment by gauravv7** [comment]
@ms-boom  why are the tests removed from setup.py?

**Comment by gauravv7** [comment]
This PR is not understandable for taking a decision to merge. 

Please describe your problem/use case for this merge request, also mention:
 - the supporting details of environment, 
 - conflicting scripts or details describing why this change

**Comment by ms-boom** [comment]
> @ms-boom why are the tests removed from setup.py?

@gauravv7 tests folder conflicts with a folder in my project because it is copied to site-packages

no need to copy tests to the site-packages root when installing the package

**Comment by hartwork** [comment]
@gauravv7 they are right, there is indeed a problem to be fixed:
```console
# python3 setup.py install --root ROOT >/dev/null ; find ROOT/ -name __init__.py
ROOT/usr/lib/python3.8/site-packages/tests/__init__.py
ROOT/usr/lib/python3.8/site-packages/easy_select2/__init__.py
```

**Comment by gauravv7** [comment]
okay, will follow

**Pull request merged**
