### PR TITLE
changelog.rst: Add missing entries, mostly for 1.5.8

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Comment by hartwork** [comment]
@asyncee @gauravv7 any concerns about me merging? I'm aware it's a new level of verbosity in the change log. Is it too much?

**Comment by asyncee** [comment]
Hi! Sorry for delay in response. The change is looking good :) I, personally, love detailed change logs. Please feel free to merge it.

**Comment by hartwork** [comment]
@asyncee is https://django-easy-select2.readthedocs.io/en/latest/changelog.html made from Git `master`? Any chance you could redeploy to Read the Docs from recent `master` to get it back into the present? Is that done manually?

**Comment by asyncee** [comment]
If i remember correctly it was automated in the past but I do not remember how exactly, possibly via CI. Please tell me your username on readthedocs and i'll intive you to the project. Thanks.

**Comment by hartwork** [comment]
@asyncee I don't have a username yet. I have zero experience with Read the Docs other than being a reader as of today :thinking:

**Comment by asyncee** [comment]
I have redeployed it yesterday.

**Comment by hartwork** [comment]
@asyncee cool, thanks! :+1:

**Pull request merged**
